### ISSUE TITLE
Feature Request for CMM hardware interaction

### ISSUE THREAD

**Issue by sammy-timalsina** [EricRosenfeld1/CalypsoAPI#3]
Have you considered implementing start, stop or pause CMM Hardware from  CalypsoAPI?

**Comment by EricRosenfeld1** [comment]
Coincidentally I am working on a set of new features right now. These also include controlling the hardware. 
I'll keep you updated in this thread.

**Comment by sammy-timalsina** [comment]
Thanks for the respond, Eric. If you would like to share your hardware communication protocol, I'd be happy to contribute to your project too.

**Comment by sammy-timalsina** [comment]
Hey Eric, For the current feature that you have in this API what is the mode of communication to get the data from the CMM? Are you parsing the file generated by the CMM, or is it some Socket communication?
